{% set name = "phreeqcrm" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phreeqcrm-{{ version }}.tar.gz
  sha256: 25899b9817e385ae1aa7968d758d0174e03a9e7f175126708d063b4646c0c062

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.20
    - make
    - ninja
    - yaml-cpp
  host:
    - python
    - scikit-build-core
    - swig
    - numpy
    - pip
    - yaml-cpp
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pyyaml
    - yaml-cpp
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]

test:
  imports:
    - phreeqcrm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usgs-coupled/phreeqcrm
  summary: A reaction module for transport simulators based on the geochemical model PHREEQC.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlparkhurst
    - scharlton2
