{% set name = "phreeqcrm" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phreeqcrm-{{ version }}.tar.gz
  sha256: bf46b102d4847153b3aaf953dd7945c5c4b00bbe0051fb6785a8ca11cf827e89

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.20
    - make
    - ninja
  host:
    - python
    - scikit-build-core
    - swig <=4.2.1
    - numpy
    - pip
  run:
    - numpy
    - python
    - pyyaml
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]

test:
  imports:
    - phreeqcrm
  commands:
    - pytest swig/python
  requires:
    - pytest
  source_files:
    - swig/python/advect.pqi
    - swig/python/AdvectBMI_py.yaml
    - swig/python/conftest.py
    - swig/python/constants.py
    - swig/python/phreeqc.dat
    - swig/python/test_basic.py
    - swig/python/test_get_value.py
    - swig/python/test_get_value.py
    - swig/python/test_init.py
    - swig/python/test_irf.py

about:
  home: https://github.com/usgs-coupled/phreeqcrm
  summary: A reaction module for transport simulators based on the geochemical model PHREEQC.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlparkhurst
    - scharlton2
